name: Test Workflow
on: [push]
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Say Hello
              run: echo "Hello, Team! The name of the workflow is ${{ github.workflow }} and the event that triggered it is ${{ github.event_name }}. the name ot the repo is ${{ github.repository }} and the branch is ${{ github.ref }}. The commit message is ${{ github.event.head_commit.message }} and the committer is ${{ github.event.head_commit.committer.name }}."