name: Test Workflow
on: [push]
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Say Hello
              run: echo "Hello, Team!"
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
                cache: npm
                cache-key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}