name: Test Workflow
on: [push]
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Say Hello
              run: echo "Hello, Team!"
    publish:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '20.x'
            registry-url: 'https://registry.npmjs.org/'
        - name: Publish to GitHub Packages
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}